import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT_DOC_CANDIDATES = ['AGENTS.md', 'CLAUDE.md'];
const SECTION_START = '<!-- agentic-managed-skills:start -->';
const SECTION_END = '<!-- agentic-managed-skills:end -->';

const SKILL_DESCRIPTIONS = {
  'agentic-bootstrap': 'Generate or audit `AGENTS.md` at the repo root.',
  'agentic-philosophy':
    'Universal agent guardrails (think before coding, verify before claiming done). Auto-loads on non-trivial work.',
  'agentic-architecture': 'Generate or audit `ARCHITECTURE.md` at the repo root.',
  'agentic-adr': 'Draft a new ADR at `doc/adr/NNNN-<slug>.md`.',
  'agentic-task': 'Draft a new task at `doc/tasks/NNNN-<slug>.md`.',
  'agentic-audit':
    'Read-only drift report comparing AGENTS.md / ARCHITECTURE.md / ADRs against the code.',
  'agentic-review':
    'Fresh-context code review per WORKFLOW §10 — assemble handoff, return structured findings.',
  'agentic-design': 'Bootstrap `DESIGN.md` from existing tokens (frontend projects).',
  'agentic-subagent': 'Draft a new Claude Code subagent at `.claude/agents/<name>.md`.',
  'agentic-skill': 'Draft a new Claude Code or Codex skill at the appropriate path.',
};

/**
 * Find the first existing root doc; null if none.
 * Preference order: AGENTS.md (open standard), then CLAUDE.md (Claude Code legacy).
 */
function findRootDoc(cwd) {
  for (const name of ROOT_DOC_CANDIDATES) {
    const path = join(cwd, name);
    if (existsSync(path)) return { name, path };
  }
  return null;
}

function buildSection(skills) {
  const lines = [];
  lines.push(SECTION_START);
  lines.push('');
  lines.push('## Skills installed by `agentic`');
  lines.push('');
  lines.push(
    'Generated by `@alexandrealvaro/agentic init`. Do not edit this section by hand — re-running the installer regenerates it. Edit the kit instead: https://github.com/alexandremendoncaalvaro/agentic-development.'
  );
  lines.push('');
  lines.push('| Skill | Invoke | Notes |');
  lines.push('| --- | --- | --- |');
  for (const skill of skills) {
    const note = SKILL_DESCRIPTIONS[skill] || '';
    const invoke =
      skill === 'agentic-philosophy' ? '_(implicit)_' : `\`/${skill}\``;
    lines.push(`| \`${skill}\` | ${invoke} | ${note} |`);
  }
  lines.push('');
  lines.push(SECTION_END);
  return lines.join('\n');
}

function replaceSection(body, newSection) {
  const startIdx = body.indexOf(SECTION_START);
  const endIdx = body.indexOf(SECTION_END);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    throw new Error('managed section markers not found or out of order');
  }
  const before = body.slice(0, startIdx);
  const after = body.slice(endIdx + SECTION_END.length);
  return before + newSection + after;
}

/**
 * Update or append the agentic-managed skills section in the project's root
 * doc (AGENTS.md preferred, CLAUDE.md as fallback). Never overwrites
 * user-authored content outside the marker block.
 *
 * Behaviour:
 *   - No root doc → returns { type: 'absent', path: null }. Skill bootstraps create the file later.
 *   - Section already present and matches → { type: 'unchanged', path }.
 *   - Section already present and stale → updated in place → { type: 'updated', path }.
 *   - Section absent → confirmAppend(path) is called; on true → appended → { type: 'appended', path }; on false → { type: 'skipped', path }.
 *
 * @param {object} opts
 * @param {string} opts.cwd  Target project root.
 * @param {string[]} opts.skills  Skill names actually installed (in display order).
 * @param {(path: string) => Promise<boolean>} [opts.confirmAppend]  Async confirmation callback for the append-to-existing-file case. Default: skip.
 */
export async function updateRootDoc({
  cwd,
  skills,
  confirmAppend = async () => false,
}) {
  const found = findRootDoc(cwd);
  if (!found) return { type: 'absent', path: null };

  const body = readFileSync(found.path, 'utf8');
  const section = buildSection(skills);

  if (body.includes(SECTION_START) && body.includes(SECTION_END)) {
    const updated = replaceSection(body, section);
    if (updated === body) return { type: 'unchanged', path: found.name };
    writeFileSync(found.path, updated);
    return { type: 'updated', path: found.name };
  }

  const ok = await confirmAppend(found.name);
  if (!ok) return { type: 'skipped', path: found.name };

  const sep = body.endsWith('\n') ? '\n' : '\n\n';
  writeFileSync(found.path, body + sep + section + '\n');
  return { type: 'appended', path: found.name };
}
