import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT_DOC_CANDIDATES = ['AGENTS.md', 'CLAUDE.md'];
const SECTION_START = '<!-- agentic-managed-skills:start -->';
const SECTION_END = '<!-- agentic-managed-skills:end -->';
// Structural anchor: the start marker is recognized only when followed by
// a blank line and the canonical managed-section heading. This prevents a
// false match if the user has the literal marker strings in their own
// content (e.g., quoting the kit's README inside a fenced code block).
// The `\r?` allowances are load-bearing, not defensive noise. Git checks the
// root doc out CRLF-terminated on Windows whenever `core.autocrlf=true` (its
// default there) and no .gitattributes overrides it. Anchored on bare \n,
// these patterns failed to recognize a section the installer had written
// itself, so it appended a second one instead of replacing the first and the
// file ended up with two contradictory skill tables.
const SECTION_START_RE = /^<!-- agentic-managed-skills:start -->\r?\n\r?\n## Skills installed by `agentic`/m;
const SECTION_END_RE = /^<!-- agentic-managed-skills:end -->\r?$/m;

// Where installed SKILL.md files live per agent. Mirrors the install layout
// (see ADR-0001). updateRootDoc is called per-target-project after install,
// so reads happen against the just-written installed copy — not the kit
// source tree (which rootdoc.js has no access to anyway).
const SKILL_PATH_BY_AGENT = {
  'claude-code': '.claude/skills',
  codex: '.agents/skills',
};

/**
 * Read the `summary:` line from an installed SKILL.md frontmatter block.
 *
 * Per task-0029, every kit skill carries a kit-specific `summary:` field
 * alongside the Anthropic-spec `description:` field. `description:` is
 * trigger-keyword-rich for the agent's skill router; `summary:` is the
 * compressed cell (≤320 chars, enforced by `test/skills.test.js`) that
 * lands in the managed AGENTS.md table.
 *
 * Tries each known target-tree location in order. Throws if no installed
 * copy has the field — a missing summary surfaces an incomplete install
 * loudly instead of silently producing empty table cells.
 */
function readSkillSummary(cwd, skill) {
  let found = false;
  for (const skillsDir of Object.values(SKILL_PATH_BY_AGENT)) {
    const path = join(cwd, skillsDir, skill, 'SKILL.md');
    if (!existsSync(path)) continue;
    found = true;
    const body = readFileSync(path, 'utf8');
    // Horizontal whitespace only between `summary:` and the value. JavaScript
    // `\s` matches `\n`, so `\s*` would silently consume the line break and
    // capture the following frontmatter line as the summary when the field
    // is present but empty. Restricting to `[ \t]*` keeps the match on one
    // line and lets an empty-summary line fall through to the throw below.
    const match = body.match(/^summary:[ \t]*(.+)$/m);
    if (match) return match[1].trim();
  }
  if (found) {
    throw new Error(
      `skill ${skill} is installed but no SKILL.md carries a non-empty \`summary:\` frontmatter field`
    );
  }
  throw new Error(
    `skill ${skill} not found at any installed location; cannot read summary`
  );
}

/**
 * Find the first existing root doc; null if none.
 * Preference order: AGENTS.md (open standard), then CLAUDE.md (Claude Code legacy).
 */
function findRootDoc(cwd) {
  for (const name of ROOT_DOC_CANDIDATES) {
    const path = join(cwd, name);
    if (existsSync(path)) return { name, path };
  }
  return null;
}

function buildSection(cwd, skills) {
  const lines = [];
  lines.push(SECTION_START);
  lines.push('');
  lines.push('## Skills installed by `agentic`');
  lines.push('');
  lines.push(
    'Generated by `@alexandrealvaro/agentic init`. Do not edit this section by hand — re-running the installer regenerates it. Edit the kit instead: https://github.com/alexandremendoncaalvaro/agentic-development.'
  );
  lines.push('');
  lines.push('| Skill | Invoke | Notes |');
  lines.push('| --- | --- | --- |');
  for (const skill of skills) {
    const note = readSkillSummary(cwd, skill);
    // ad-philosophy auto-loads as posture, but an explicit `/ad-philosophy`
    // is a distinct mode (ADR-0044), so the table must advertise both.
    const invoke =
      skill === 'ad-philosophy'
        ? `\`/${skill}\` _(also implicit)_`
        : `\`/${skill}\``;
    lines.push(`| \`${skill}\` | ${invoke} | ${note} |`);
  }
  lines.push('');
  lines.push(SECTION_END);
  return lines.join('\n');
}

function findSectionBounds(body) {
  const startMatch = body.match(SECTION_START_RE);
  if (!startMatch) return null;
  const startIdx = startMatch.index;
  const tail = body.slice(startIdx + SECTION_START.length);
  const endMatch = tail.match(SECTION_END_RE);
  if (!endMatch) return null;
  const endIdx = startIdx + SECTION_START.length + endMatch.index;
  return { startIdx, endIdx };
}

function replaceSection(body, newSection, bounds) {
  const before = body.slice(0, bounds.startIdx);
  const after = body.slice(bounds.endIdx + SECTION_END.length);
  return before + newSection + after;
}

/**
 * Message and default for the interactive "regenerate the managed section?"
 * confirmation on a git-tracked root doc (ADR-0050 Decision 2). Names both
 * risks — the file is shared with everyone who clones the repo, and edits
 * between the markers are lost — and defaults to no. Used only when the doc is
 * tracked; the untracked case keeps each command's prior replace behaviour.
 * Pure and separate from the TUI so the decision is unit-testable.
 */
export function rootDocReplacePrompt(path) {
  return {
    message:
      `${path} is tracked by git — regenerating the managed ` +
      `"Skills installed by agentic" section changes a file shared with ` +
      `everyone who clones the repo, and any edits between the markers are ` +
      `lost. Regenerate it anyway?`,
    initialValue: false,
  };
}

/**
 * The stderr line an unattended run prints when it declines to write a managed
 * section into a git-tracked root doc (ADR-0050). Shared by init and update so
 * the wording — the part most likely to drift between two call sites — lives in
 * one place; the trivial guard that calls it stays local to each command.
 */
export function trackedRootDocSkipNotice(path) {
  return (
    `skipped ${path}: tracked by git, so the managed section would be ` +
    `visible to everyone sharing this repository. Re-run interactively ` +
    `to decide, or pass --force-root-doc.`
  );
}

/**
 * Message and default answer for the interactive "append the managed section?"
 * confirmation, given the root doc's name and its git tracking state.
 *
 * A tracked root doc is shared with everyone who clones the repository, so the
 * prompt says exactly that and stops pre-answering yes (ADR-0050). The previous
 * wording spoke only to content ("existing content preserved"), which reassures
 * about the wrong risk: the hazard is not losing text, it is publishing a
 * section into someone else's document.
 *
 * `unknown` is treated as `untracked` on purpose — absence of evidence that the
 * file is shared is not evidence that it is, and a warning the user cannot act
 * on trains them to dismiss the ones that matter.
 *
 * Pure and separate from the TUI so the decision is testable: the suite runs
 * without a TTY and cannot drive the prompt itself.
 */
export function rootDocAppendPrompt(path, tracked) {
  if (tracked === 'tracked') {
    return {
      message:
        `${path} is tracked by git — this section will be visible to ` +
        `everyone who shares the repository. Append the managed ` +
        `"Skills installed by agentic" section anyway?`,
      initialValue: false,
    };
  }
  return {
    message: `Append a managed "Skills installed by agentic" section to ${path}? (existing content preserved)`,
    initialValue: true,
  };
}

/**
 * Update or append the agentic-managed skills section in the project's root
 * doc (AGENTS.md preferred, CLAUDE.md as fallback). Never overwrites
 * user-authored content outside the marker block.
 *
 * Behaviour:
 *   - No root doc → returns { type: 'absent', path: null }. Skill bootstraps create the file later.
 *   - Section already present and matches → { type: 'unchanged', path }.
 *   - Section already present and stale → confirmReplace(path) is called; on true → updated → { type: 'updated', path }; on false → { type: 'kept-stale', path } (managed-section diverged on disk and the user chose to keep it).
 *   - Section absent → confirmAppend(path) is called; on true → appended → { type: 'appended', path }; on false → { type: 'skipped', path }.
 *   - dryRun true → no writes; returned `type` reflects what *would* happen.
 *
 * @param {object} opts
 * @param {string} opts.cwd  Target project root.
 * @param {string[]} opts.skills  Skill names actually installed (in display order).
 * @param {(path: string) => Promise<boolean>} [opts.confirmAppend]  Async confirmation callback for the append-to-existing-file case. Default: skip.
 * @param {(path: string) => Promise<boolean>} [opts.confirmReplace]  Async confirmation callback for the replace-existing-section case (managed section present on disk but stale). Default: replace (preserves the v0.5 behaviour where update silently regenerates the managed block on every kit / skill change). Wire to a prompt to honor user edits between markers.
 * @param {boolean} [opts.dryRun]  When true, computes the action without writing.
 */
export async function updateRootDoc({
  cwd,
  skills,
  confirmAppend = async () => false,
  confirmReplace = async () => true,
  dryRun = false,
}) {
  const found = findRootDoc(cwd);
  if (!found) return { type: 'absent', path: null };

  const body = readFileSync(found.path, 'utf8');
  const bounds = findSectionBounds(body);

  // Build the section lazily — readSkillSummary touches the installed
  // SKILL.md files (per task-0029). When the user declines a section
  // append/replace, there is no reason to walk every installed skill.
  if (bounds) {
    const section = buildSection(cwd, skills);
    const updated = replaceSection(body, section, bounds);
    if (updated === body) return { type: 'unchanged', path: found.name };
    const ok = await confirmReplace(found.name);
    if (!ok) return { type: 'kept-stale', path: found.name };
    if (!dryRun) writeFileSync(found.path, updated);
    return { type: 'updated', path: found.name };
  }

  const ok = await confirmAppend(found.name);
  if (!ok) return { type: 'skipped', path: found.name };

  const section = buildSection(cwd, skills);
  const sep = body.endsWith('\n') ? '\n' : '\n\n';
  if (!dryRun) writeFileSync(found.path, body + sep + section + '\n');
  return { type: 'appended', path: found.name };
}
