import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT_DOC_CANDIDATES = ['AGENTS.md', 'CLAUDE.md'];
const SECTION_START = '<!-- agentic-managed-skills:start -->';
const SECTION_END = '<!-- agentic-managed-skills:end -->';
// Structural anchor: the start marker is recognized only when followed by
// a blank line and the canonical managed-section heading. This prevents a
// false match if the user has the literal marker strings in their own
// content (e.g., quoting the kit's README inside a fenced code block).
const SECTION_START_RE = /^<!-- agentic-managed-skills:start -->\n\n## Skills installed by `agentic`/m;
const SECTION_END_RE = /^<!-- agentic-managed-skills:end -->$/m;

export const SKILL_DESCRIPTIONS = {
  'agentic-bootstrap': 'Generate or audit `AGENTS.md` at the repo root.',
  'agentic-philosophy':
    'Universal agent guardrails (think before coding, verify before claiming done). Auto-loads on non-trivial work.',
  'agentic-architecture': 'Generate or audit `ARCHITECTURE.md` at the repo root.',
  'agentic-adr': 'Draft a new ADR at `doc/adr/NNNN-<slug>.md`.',
  'agentic-spec':
    'Draft a feature spec at `doc/specs/NNNN-<slug>.md` (Spec Kit-aligned mandatory sections). Layer 2 of the four-layer artifact stack.',
  'agentic-task': 'Draft a new task at `doc/tasks/NNNN-<slug>.md`.',
  'agentic-audit':
    'Read-only drift report comparing AGENTS.md / ARCHITECTURE.md / ADRs against the code.',
  'agentic-review':
    'Fresh-context code review per WORKFLOW §10 — assemble handoff, return structured findings.',
  'agentic-ground':
    'Four-source pre-implementation research (docs / OSS / in-repo / git history) + happy-path synthesis + deviation gate. WORKFLOW §4 + §5.',
  'agentic-next':
    'State survey + prioritized next-action recommendations across the four-layer artifact stack. Read-only navigation aid (`flutter doctor` pattern).',
  'agentic-spike':
    'Staged spike with golden fixtures per WORKFLOW §14. Discovery + fixture + pipeline-with-gates + two-layer evaluation, when the *technique* is uncertain across multiple plausible approaches.',
  'agentic-design': 'Bootstrap `DESIGN.md` from existing tokens (frontend projects).',
  'agentic-subagent': 'Draft a new Claude Code subagent at `.claude/agents/<name>.md`.',
  'agentic-skill': 'Draft a new Claude Code or Codex skill at the appropriate path.',
  'agentic-hooks':
    'Scaffold deterministic quality gates per WORKFLOW §11 — pre-commit + pre-push, runner detected from stack signals.',
};

/**
 * Find the first existing root doc; null if none.
 * Preference order: AGENTS.md (open standard), then CLAUDE.md (Claude Code legacy).
 */
function findRootDoc(cwd) {
  for (const name of ROOT_DOC_CANDIDATES) {
    const path = join(cwd, name);
    if (existsSync(path)) return { name, path };
  }
  return null;
}

function buildSection(skills) {
  const lines = [];
  lines.push(SECTION_START);
  lines.push('');
  lines.push('## Skills installed by `agentic`');
  lines.push('');
  lines.push(
    'Generated by `@alexandrealvaro/agentic init`. Do not edit this section by hand — re-running the installer regenerates it. Edit the kit instead: https://github.com/alexandremendoncaalvaro/agentic-development.'
  );
  lines.push('');
  lines.push('| Skill | Invoke | Notes |');
  lines.push('| --- | --- | --- |');
  for (const skill of skills) {
    const note = SKILL_DESCRIPTIONS[skill] || '';
    const invoke =
      skill === 'agentic-philosophy' ? '_(implicit)_' : `\`/${skill}\``;
    lines.push(`| \`${skill}\` | ${invoke} | ${note} |`);
  }
  lines.push('');
  lines.push(SECTION_END);
  return lines.join('\n');
}

function findSectionBounds(body) {
  const startMatch = body.match(SECTION_START_RE);
  if (!startMatch) return null;
  const startIdx = startMatch.index;
  const tail = body.slice(startIdx + SECTION_START.length);
  const endMatch = tail.match(SECTION_END_RE);
  if (!endMatch) return null;
  const endIdx = startIdx + SECTION_START.length + endMatch.index;
  return { startIdx, endIdx };
}

function replaceSection(body, newSection, bounds) {
  const before = body.slice(0, bounds.startIdx);
  const after = body.slice(bounds.endIdx + SECTION_END.length);
  return before + newSection + after;
}

/**
 * Update or append the agentic-managed skills section in the project's root
 * doc (AGENTS.md preferred, CLAUDE.md as fallback). Never overwrites
 * user-authored content outside the marker block.
 *
 * Behaviour:
 *   - No root doc → returns { type: 'absent', path: null }. Skill bootstraps create the file later.
 *   - Section already present and matches → { type: 'unchanged', path }.
 *   - Section already present and stale → confirmReplace(path) is called; on true → updated → { type: 'updated', path }; on false → { type: 'kept-stale', path } (managed-section diverged on disk and the user chose to keep it).
 *   - Section absent → confirmAppend(path) is called; on true → appended → { type: 'appended', path }; on false → { type: 'skipped', path }.
 *   - dryRun true → no writes; returned `type` reflects what *would* happen.
 *
 * @param {object} opts
 * @param {string} opts.cwd  Target project root.
 * @param {string[]} opts.skills  Skill names actually installed (in display order).
 * @param {(path: string) => Promise<boolean>} [opts.confirmAppend]  Async confirmation callback for the append-to-existing-file case. Default: skip.
 * @param {(path: string) => Promise<boolean>} [opts.confirmReplace]  Async confirmation callback for the replace-existing-section case (managed section present on disk but stale). Default: replace (preserves the v0.5 behaviour where update silently regenerates the managed block on every kit / skill change). Wire to a prompt to honor user edits between markers.
 * @param {boolean} [opts.dryRun]  When true, computes the action without writing.
 */
export async function updateRootDoc({
  cwd,
  skills,
  confirmAppend = async () => false,
  confirmReplace = async () => true,
  dryRun = false,
}) {
  const found = findRootDoc(cwd);
  if (!found) return { type: 'absent', path: null };

  const body = readFileSync(found.path, 'utf8');
  const section = buildSection(skills);
  const bounds = findSectionBounds(body);

  if (bounds) {
    const updated = replaceSection(body, section, bounds);
    if (updated === body) return { type: 'unchanged', path: found.name };
    const ok = await confirmReplace(found.name);
    if (!ok) return { type: 'kept-stale', path: found.name };
    if (!dryRun) writeFileSync(found.path, updated);
    return { type: 'updated', path: found.name };
  }

  const ok = await confirmAppend(found.name);
  if (!ok) return { type: 'skipped', path: found.name };

  const sep = body.endsWith('\n') ? '\n' : '\n\n';
  if (!dryRun) writeFileSync(found.path, body + sep + section + '\n');
  return { type: 'appended', path: found.name };
}
